name: review
on:
  pull_request:
    paths:
      - '*.c'
      - '*.h'
jobs:
  upstream_tests:
     if: ${{ github.repository == 'md-raid-utilities/mdadm' }}
     runs-on: self-hosted
     timeout-minutes: 90
     name: upstream tests
     steps:
     - uses: actions/checkout@v4
       with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
     - name: 'Prepare machine'
       run: |
          cd ..
          vagrant halt
          vagrant status
          vagrant up
     - name: 'Run tests'
       run: |
          cd ..
          vagrant ssh -c "cd /home/vagrant/host/mdadm && .github/tools/run_mdadm_tests.sh"
     - uses: actions/download-artifact@v4
       with:
         name: /var/tmp/*.log
  cleanup:
    runs-on: self-hosted
    steps:
      - name: Restore clean VM
        run:  |
          cd ..
          vagrant halt
      - name: Stop md devices
        run: sudo mdadm -Ss
      - name: Clean logs
        run: rm -rf /var/tmp/*.log
